# Используйте официальный образ Python с нужной версией
FROM python:3.11.9

# Установите переменную окружения PYTHONUNBUFFERED, чтобы предотвратить буферизацию вывода
ENV PYTHONUNBUFFERED 1

# Установите рабочую директорию внутри контейнера
WORKDIR /app

# Скопируйте файл requirements.txt в контейнер
COPY requirements.txt /app/

# Установите зависимости Python из requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Скопируйте все содержимое текущей директории в контейнер
COPY . /app/

# Определите порт, который будет слушаться внутри контейнера
EXPOSE 8000

# Команда для запуска сервера Django при старте контейнера
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]